# Generated by Django 5.2.5 on 2025-08-12 16:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceBook', '0005_alter_to_dateorder_alter_to_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to',
            name='dateOrder',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='to',
            name='dateTO',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='serviceBook.machine')),
                ('dateFailure', models.DateTimeField(default=datetime.datetime.today)),
                ('runTime', models.IntegerField(default=0)),
                ('descriptionFailure', models.TextField()),
                ('spareParts', models.TextField()),
                ('dateRetraiding', models.DateTimeField(default=datetime.datetime.today)),
                ('failureNode', models.ForeignKey(limit_choices_to={'nameClass': 'FND'}, on_delete=django.db.models.deletion.CASCADE, related_name='failureNode', to='serviceBook.manual')),
                ('serviceCompanyR', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serviceCompanyR', to='serviceBook.service')),
                ('wayToRecover', models.ForeignKey(limit_choices_to={'nameClass': 'WTR'}, on_delete=django.db.models.deletion.CASCADE, related_name='wayToRecover', to='serviceBook.manual')),
            ],
        ),
    ]
